# Generated by Django 4.2.6 on 2023-10-06 20:33

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('ip_address', models.CharField(max_length=20, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('subTitle', models.CharField(max_length=255)),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('readingTime', models.IntegerField()),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Trends', 'Trends'), ('Developer Tools', 'Developer Tools'), ('Discover', 'Discover')], max_length=25)),
                ('mdContent', mdeditor.fields.MDTextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
