# Generated by Django 4.2.6 on 2023-10-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='token',
        ),
        migrations.AddField(
            model_name='member',
            name='tokenData',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
