# Generated by Django 4.2.6 on 2023-10-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='member',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
