# Generated by Django 4.2.6 on 2023-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contact_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='member',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
