# Generated by Django 4.2.6 on 2023-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contact_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='member',
        ),
        migrations.AddField(
            model_name='contact',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
