# Generated by Django 4.2.6 on 2023-10-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_contact_member_contact_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('wd', 'Web Development'), ('t', 'Trends'), ('dt', 'Developer Tools'), ('d', 'Discover')], max_length=25),
        ),
    ]
