# Generated by Django 4.2.6 on 2023-10-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('web-development', 'Web Development'), ('trends', 'Trends'), ('developer-tools', 'Developer Tools'), ('discover', 'Discover')], max_length=25),
        ),
    ]
