# Generated by Django 4.2.6 on 2023-10-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
    ]
