# Generated by Django 4.2.6 on 2023-10-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COMMENT',
        ),
    ]
