# Generated by Django 4.2.6 on 2023-10-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('blog', '0015_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CONTACT',
        ),
        migrations.AlterField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='member.member', to_field='userName'),
        ),
        migrations.DeleteModel(
            name='MEMBER',
        ),
    ]
