# Generated by Django 4.2.6 on 2023-11-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_delete_subscribevisitors'),
        ('blog', '0019_remove_post_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST_SAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(blank=True, default=False, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='member.member', to_field='userName')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='POST_LIKE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(blank=True, default=False, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='member.member', to_field='userName')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='blog.post')),
            ],
        ),
    ]
