# Generated by Django 4.2.6 on 2023-11-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_save_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_like',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post_save',
            name='saves_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
