# Generated by Django 4.2.6 on 2023-11-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_like_likes_count_post_save_saves_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_like',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post_save',
            name='saves_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
