# Generated by Django 4.2.6 on 2023-11-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_like_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_like',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='post_save',
            name='saves_count',
        ),
    ]
