# Generated by Django 4.2.6 on 2023-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tokenData',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
