# Generated by Django 4.2.6 on 2023-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
