# Generated by Django 4.2.6 on 2023-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_socialmedialink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(blank=True, choices=[('x', 'X'), ('github', 'GitHub'), ('linkedin', 'LinkedIn')], max_length=30, null=True),
        ),
    ]
