# Generated by Django 4.2.6 on 2023-11-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='platform',
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
