# Generated by Django 4.2.6 on 2023-11-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_rename_twitter_url_socialmedialink_x_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
