# Generated by Django 4.2.6 on 2023-11-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_socialmedialink_create_at_socialmedialink_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='x_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
