# Generated by Django 4.2.6 on 2023-11-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_email_subscribe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
