# Generated by Django 4.2.6 on 2023-11-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_subscribevisitors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeVisitors',
        ),
    ]
